title: Simple Neural Network
description: Step-by-step example of a Single Layer NN from Scratch in R.
google_analytics: UA-173072064-1
show_downloads: false
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
